# Generated by Django 5.1.7 on 2025-03-22 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TheDate', models.DateField(auto_now_add=True)),
                ('Region', models.CharField(choices=[('Central', 'Central'), ('East', 'East'), ('West', 'West')], max_length=50)),
                ('Rep', models.CharField(max_length=50)),
                ('Items', models.CharField(choices=[('Pencil', 'Pencil'), ('Pen', 'Pen'), ('Binder', 'Binder'), ('Desk', 'Desk'), ('Pen Set', 'Pen Set')], max_length=50)),
                ('Units', models.IntegerField()),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
